title: Pereni Srikandi's Toshokan
author: alapereni
email: alapereni@gmail.com
description: You can find like the title it was "Toshokan" its mean "library" also Toshokan is from Japanese language so the main topic is from Japan. You can find everything about novels, comics, and sometimes Japanese learning. 
theme: minami
# social links
twitter_username: Pereni
github_username:  alapereni
show_excerpts: false
